import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import "../styles/footer.scss";
import SocialSidebar from "@/components/SocialSidebar";

import TopHeader from '@/components/Top-Header';
import BottomHeader from '@/components/Bottom-Header';
import "../styles/header.scss";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Travel UI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />  

        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
        />

        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        />
      </head>

      {/* ⭐ FIXED BODY ⭐ */}
      <body className="min-h-screen overflow-visible">
        <Providers>
        <TopHeader />
        <BottomHeader />
        <SocialSidebar />
        {children}
        <Footer />
        </Providers>
      </body>
    </html>
  );
}
