export const tripLists = [
    {
      id: 1,
      name: "Andaman Family Trip",
      slug: "family-trip",
      title: "Exciting Family Adventures",
      description: "Enjoy a memorable trip with your family, exploring scenic destinations and fun activities for all ages.",
      availableTickets: 50,
      location: "Goa, India",
      servicesAvailable: ["Meals", "Hotel Stay", "Sightseeing", "Travel Insurance"],
      imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
      price: 'Rs 12000',
      duration: "7 Nights / 8 Days",
      offer:'30%',
      destinations:'Andman & Nicobar'
    },
    {
      id: 2,
      name: "Andaman Honeymoon Trip",
      slug: "honeymoon-trip",
      title: "Romantic Getaways",
      description: "Perfect trips for couples to celebrate love, featuring romantic destinations and cozy accommodations.",
      availableTickets: 30,
      location: "Maldives",
      servicesAvailable: ["Private Beach", "Couple Spa", "Romantic Dinner", "Travel Guide"],
      imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      price: 'Rs 2500',
      duration: "5 Nights / 6 Days",
      offer:'40%',
      destinations:'Andman & Nicobar'
    },
    {
      id: 3,
      name: "Andaman Group Trip",
      slug: "group-trip",
      title: "Fun Group Excursions",
      description: "Ideal for friends or colleagues who want to explore destinations together with group activities.",
      availableTickets: 100,
      location: "Rishikesh, India",
      servicesAvailable: ["Rafting", "Camping", "Team Games", "Travel Guide"],
      imageUrl: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80",
      price: 'Rs 8000',
      duration: "3 Nights / 4 Days",
      offer:'50%',
      destinations:'Andman & Nicobar'
    },
    {
      id: 4,
      name: "Andaman WeekEnd Trip",
      slug: "weekend-trip",
      title: "Quick Weekend Escapes",
      description: "Short trips to refresh your mind and enjoy a break from the daily routine over the weekend.",
      availableTickets: 40,
      location: "Lonavala, India",
      servicesAvailable: ["Resort Stay", "Sightseeing", "Adventure Sports"],
      imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      price: 'Rs 5000',
      duration: "2 Nights / 3 Days",
       offer:'20%',
       destinations:'Andman & Nicobar'
    },
    {
      id: 5,
      name: "Andaman Regular Trip",
      slug: "regular-trip",
      title: "Standard Travel Packages",
      description: "Regular trips with balanced activities and sightseeing for a relaxed and enjoyable experience.",
      availableTickets: 60,
      location: "Jaipur, India",
      servicesAvailable: ["Hotel Stay", "City Tour", "Meals"],
      imageUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=800&q=80",
      price: 'Rs 7000',
      duration: "4 Nights / 5 Days",
      offer:'30%',
      destinations:'Andman & Nicobar'
    },
    {
      id: 6,
      name: "Andaman Custom Trip",
      slug: "custom-trip",
      title: "Tailor-Made Journeys",
      description: "Design your own trip according to your interests and preferences with flexible options.",
      availableTickets: 20,
      location: "Choose Your Destination",
      servicesAvailable: ["Custom Itinerary", "Personal Guide", "Luxury Stay", "Special Requests"],
      imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
      price: 'Rs 3000',
      duration: "Flexible",
      offer:'40%',
      destinations:'Andman & Nicobar'
    }
  ];
  